apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: mysql:5.7
    name: mysql
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "sleep 15 && mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'CREATE DATABASE IF NOT EXISTS assad'"]
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "123456"